local hl = vim.api.nvim_set_hl

--hl(0, "Comment", { link = "Normal" }) -- any comment
hl(0, "Constant", { link = "String" }) -- any constant
--hl(0, "String", { link = "Normal" }) -- a string constant: "this is a string"
hl(0, "Character", { link = "Constant" }) -- a character constant: 'c', '\n'
hl(0, "Number", { link = "Constant" }) -- a number constant: 233, 0xff
hl(0, "Boolean", { link = "Constant" }) -- a boolean constant: TRUE, false
hl(0, "Float", { link = "Constant" }) -- a floating point constant: 2.3e10
hl(0, "Identifier", { link = "Function" }) -- any variable name
--hl(0, "Function", { link = "Normal" }) -- function name (also: methods for classes)
hl(0, "Statement", { link = "Normal" }) -- any statement
hl(0, "Conditional", { link = "Statement" }) -- if, then, else, endif, switch, etc.
hl(0, "Repeat", { link = "Statement" }) -- for, do, while, etc.
hl(0, "Label", { link = "Statement" }) -- case, default, etc.
hl(0, "Operator", { link = "Statement" }) -- "sizeof", "+", "*", etc.
hl(0, "Keyword", { link = "Statement" }) -- any other keyword
hl(0, "Exception", { link = "Statement" }) -- try, catch, throw
hl(0, "PreProc", { link = "Statement" }) -- generic Preprocessor
hl(0, "Include", { link = "Statement" }) -- preprocessor #include
hl(0, "Define", { link = "Statement" }) -- preprocessor #define
hl(0, "Macro", { link = "Statement" }) -- same as Define
hl(0, "PreCondit", { link = "Statement" }) -- preprocessor #if, #else, #endif, etc.
hl(0, "Type", { link = "Statement" }) -- int, long, char, etc.
hl(0, "StorageClass", { link = "Statement" }) -- static, register, volatile, etc.
hl(0, "Structure", { link = "Function" }) -- struct, union, enum, etc.
hl(0, "Typedef", { link = "Statement" }) -- a typedef
-- hl(0, "Special", { link = "Statement" }) -- any special symbol
-- hl(0, "SpecialChar", { link = "Statement" }) -- special character in a constant
-- hl(0, "Tag", { link = "Function" }) -- you can use CTRL-] on this
-- hl(0, "Delimiter", { link = "Statement" }) -- character that needs attention
-- hl(0, "SpecialComment", { link = "Comment" }) -- special things inside a comment
--hl(0, "Debug", { link = "Statement" }) -- debugging statements
--hl(0, "Underlined", { link = "Normal" }) -- text that stands out, HTML links
--hl(0, "Ignore", { link = "Normal" }) -- left blank, hidden  |hl-Ignore|
--hl(0, "Error", { link = "Normal" }) -- any erroneous construct
--hl(0, "Todo", { link = "Normal" }) -- anything that needs extra attention; mostly the
--hl(0, "Added", { link = "Normal" }) -- added line in a diff
--hl(0, "Changed", { link = "Normal" }) -- changed line in a diff
--hl(0, "Removed", { link = "Normal" }) -- removed line in a diff

--[[
hl(0, "@lsp.type.class", { link = "Function" })
hl(0, "@lsp.type.comment", { link = "Comment" })
hl(0, "@lsp.type.decorator", { link = "Comment" })
hl(0, "@lsp.type.enum", { link = "Function" })
hl(0, "@lsp.type.enumMember", { link = "Function" })
hl(0, "@lsp.type.event", { link = "Function" })
hl(0, "@lsp.type.function", { link = "Function" })
hl(0, "@lsp.type.interface", { link = "Function" })
hl(0, "@lsp.type.keyword", { link = "Keyword" })
hl(0, "@lsp.type.macro", { link = "Function" })
hl(0, "@lsp.type.method", { link = "Function" })
hl(0, "@lsp.type.modifier", { link = "Function" })
hl(0, "@lsp.type.namespace", { link = "Function" })
hl(0, "@lsp.type.number", { link = "Constant" })
hl(0, "@lsp.type.operator", { link = "Statement" })
hl(0, "@lsp.type.parameter", { link = "Statement" })
hl(0, "@lsp.type.property", { link = "Statement" })
hl(0, "@lsp.type.regexp", { link = "String" })
hl(0, "@lsp.type.string", { link = "String" })
hl(0, "@lsp.type.struct", { link = "Structure" })
hl(0, "@lsp.type.type", { link = "Function" })
hl(0, "@lsp.type.typeParameter", { link = "Statement" })
hl(0, "@lsp.type.variable", { link = "Function" })
hl(0, "@lsp.mod.abstract", { link = "Statement" })
hl(0, "@lsp.mod.async", { link = "Statement" })
hl(0, "@lsp.mod.declaration", { link = "Function" })
hl(0, "@lsp.mod.defaultLibrary", { link = "Statement" })
hl(0, "@lsp.mod.definition", { link = "Statement" })
hl(0, "@lsp.mod.deprecated", { link = "Deprecated" })
hl(0, "@lsp.mod.documentation", { link = "Comment" })
hl(0, "@lsp.mod.modification", { link = "Statement" })
hl(0, "@lsp.mod.readonly", { link = "Statement" })
hl(0, "@lsp.mod.static", { link = "Statement" })

hl(0, "@variable", { link = "Normal" })
hl(0, "@variable.builtin", { link = "Normal" })
hl(0, "@variable.parameter", { link = "Normal" })
hl(0, "@variable.parameter", { link = "Normal" })
hl(0, "@variable.member", { link = "Normal" })
hl(0, "@constant", { link = "Normal" })
hl(0, "@constant.builtin", { link = "Normal" })
hl(0, "@constant.macro", { link = "Normal" })
hl(0, "@module", { link = "Normal" })
hl(0, "@module.builtin", { link = "Normal" })
hl(0, "@label", { link = "Normal" })
hl(0, "@string", { link = "Normal" })
hl(0, "@string.documentation", { link = "Normal" })
hl(0, "@string.regexp", { link = "Normal" })
hl(0, "@string.escape", { link = "Normal" })
hl(0, "@string.special", { link = "Normal" })
hl(0, "@string.special", { link = "Normal" })
hl(0, "@string.special", { link = "Normal" })
hl(0, "@string.special", { link = "Normal" })
hl(0, "@character", { link = "Normal" })
hl(0, "@character.special", { link = "Normal" })
hl(0, "@boolean", { link = "Normal" })
hl(0, "@number", { link = "Normal" })
hl(0, "@number.float", { link = "Normal" })
hl(0, "@type", { link = "Normal" })
hl(0, "@type.builtin", { link = "Normal" })
hl(0, "@type.definition", { link = "Normal" })
hl(0, "@attribute", { link = "Normal" })
hl(0, "@attribute.builtin", { link = "Normal" })
hl(0, "@property", { link = "Normal" })
hl(0, "@function", { link = "Normal" })
hl(0, "@function.builtin", { link = "Normal" })
hl(0, "@function.call", { link = "Normal" })
hl(0, "@function.macro", { link = "Normal" })
hl(0, "@function.method", { link = "Normal" })
hl(0, "@function.method", { link = "Normal" })
hl(0, "@constructor", { link = "Normal" })
hl(0, "@operator", { link = "Normal" })
hl(0, "@keyword", { link = "Normal" })
hl(0, "@keyword.coroutine", { link = "Normal" })
hl(0, "@keyword.function", { link = "Normal" })
hl(0, "@keyword.operator", { link = "Normal" })
hl(0, "@keyword.import", { link = "Normal" })
hl(0, "@keyword.type", { link = "Normal" })
hl(0, "@keyword.modifier", { link = "Normal" })
hl(0, "@keyword.repeat", { link = "Normal" })
hl(0, "@keyword.return", { link = "Normal" })
hl(0, "@keyword.debug", { link = "Normal" })
hl(0, "@keyword.exception", { link = "Normal" })
hl(0, "@keyword.conditional", { link = "Normal" })
hl(0, "@keyword.conditional", { link = "Normal" })
hl(0, "@keyword.directive", { link = "Normal" })
hl(0, "@keyword.directive", { link = "Normal" })
hl(0, "@punctuation.delimiter", { link = "Normal" })
hl(0, "@punctuation.bracket", { link = "Normal" })
hl(0, "@punctuation.special", { link = "Normal" })
hl(0, "@comment", { link = "Normal" })
hl(0, "@comment.documentation", { link = "Normal" })
hl(0, "@comment.error", { link = "Normal" })
hl(0, "@comment.warning", { link = "Normal" })
hl(0, "@comment.todo", { link = "Normal" })
hl(0, "@comment.note", { link = "Normal" })
hl(0, "@markup.strong", { link = "Normal" })
hl(0, "@markup.italic", { link = "Normal" })
hl(0, "@markup.strikethrough", { link = "Normal" })
hl(0, "@markup.underline", { link = "Normal" })
hl(0, "@markup.heading", { link = "Normal" })
hl(0, "@markup.heading.1", { link = "Normal" })
hl(0, "@markup.heading.2", { link = "Normal" })
hl(0, "@markup.heading.3", { link = "Normal" })
hl(0, "@markup.heading.4", { link = "Normal" })
hl(0, "@markup.heading.5", { link = "Normal" })
hl(0, "@markup.heading.6", { link = "Normal" })
hl(0, "@markup.quote", { link = "Normal" })
hl(0, "@markup.math", { link = "Normal" })
hl(0, "@markup.link", { link = "Normal" })
hl(0, "@markup.link.label", { link = "Normal" })
hl(0, "@markup.link.url", { link = "Normal" })
hl(0, "@markup.raw", { link = "Normal" })
hl(0, "@markup.raw.block", { link = "Normal" })
hl(0, "@markup.list", { link = "Normal" })
hl(0, "@markup.list.checked", { link = "Normal" })
hl(0, "@markup.list.unchecked", { link = "Normal" })
hl(0, "@diff.plus", { link = "Normal" })
hl(0, "@diff.minus", { link = "Normal" })
hl(0, "@diff.delta", { link = "Normal" })
hl(0, "@tag", { link = "Normal" })
hl(0, "@tag.builtin", { link = "Normal" })
hl(0, "@tag.attribute", { link = "Normal" })
hl(0, "@tag.delimiter", { link = "Normal" })
]]--
